# Generated by Django 4.1.2 on 2022-10-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_attendance_classroom_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='sub',
        ),
        migrations.AddField(
            model_name='classroom',
            name='student_attendance',
            field=models.ManyToManyField(blank=True, related_name='classrooms', to='accounts.attendance'),
        ),
    ]
