# Generated by Django 4.1.2 on 2022-10-28 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_attendance_sub_classroom_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='student_attendance',
        ),
    ]
