# Generated by Django 4.1.2 on 2022-10-28 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_classroom_student_attendance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='classroom_id',
            new_name='subject',
        ),
    ]
