# Generated by Django 4.1.2 on 2022-10-28 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_classroom_id_attendance_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sub',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
