# Generated by Django 4.0.2 on 2022-11-14 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_classroom_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='course',
            field=models.CharField(default='N/A', max_length=200),
        ),
    ]
