# Generated by Django 4.0.2 on 2023-01-25 03:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_student_consent_teacher_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='code',
            field=models.SlugField(default=accounts.models.random_string, max_length=5, unique=True, verbose_name='Subject Code'),
        ),
    ]
