# Generated by Django 4.0.2 on 2023-02-15 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_teacher_stream_delete_stream'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='course',
            field=models.CharField(default='Forgotten', max_length=200),
        ),
    ]
