# Generated by Django 4.0.2 on 2023-04-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_ftf_attendance_ftf_student_delete_lastface_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ftf_attendance',
            name='period',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
