# Generated by Django 4.0.2 on 2023-04-05 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_ftf_attendance_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FTF_Attendance',
        ),
        migrations.DeleteModel(
            name='FTF_Student',
        ),
    ]
